import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
const read=async file=>JSON.parse(await readFile(file,'utf8'));
const [performance,native,contract,checks]=await Promise.all([
 read('output/building-performance/report.json'),read('output/building-native/report.json'),
 read('output/building-contract/report.json'),read('output/building-acceptance/report.json'),
]);
const link=file=>path.resolve(file).replaceAll('\\','/');
const n=value=>Number(value).toFixed(1);
const delivery=await read('output/building-delivery.json').catch(()=>({status:'Candidate under final validation; shared preview has not been replaced.'}));
let report=`# Building, access and jump verification\n\nGenerated ${new Date().toISOString()}. Branch: codex/building-concept-access. Protected baseline: f69269e. ${delivery.status}\n\n`;
report+=`## Functional checks\n\n- Native tour: ${native.passed?'PASS':'FAIL'}, ${native.checks.length} waypoints, ${n(native.elapsedMs/1000)} seconds, five apprentices, real W-key input and no teleport during the route. Main, west, east and street rooms, L1-L4, garage, B1/B2, and original-room exit/re-entry after five minutes.\n- The user's delayed original-area blockage was not reproduced. These results do not establish its cause.\n- Metric surfaces: ${contract.uv.meshes} meshes / ${contract.uv.edges} checked planar edges; ${contract.uv.errors.length} density errors.\n- Masonry: ${contract.masonry.tested} aimable partitions; six native held-tool work samples; ${contract.save.before} removed nodes preserved by editor save/restore.\n- Window sill removal/restoration: ${JSON.stringify(contract.windowOpening)}.\n\n`;
for(const check of checks)report+=`- ${check.name}: ${check.passed?'PASS':'FAIL'}; [log](${link(check.log)}).\n`;
const [jump,motion,entry]=await Promise.all([read('output/building-jump/report.json'),read('output/building-jump-animation/report.json'),read('output/building-foyer-entry/after/report.json')]);
report+=`\n## Jump and direct stair entrance\n\n- The approach in the submitted image now crosses a real opening and threshold: ${entry.passed?'PASS':'FAIL'}.\n- Space and matching Jump button beside Stand/Crouch: ${jump.passed?'PASS':'FAIL'}, desktop, phone, tablet and landscape emulation.\n- Fourteen stair/doorway positions: minimum measured overhead clearance ${n(Math.min(...jump.profiles.flatMap(p=>p.cases.map(c=>c.clearance))))} m; jump height approximately 0.516 m. Head collision uses the actual structural underside.\n- ${motion.cases.length} tool poses: ${motion.passed?'PASS':'FAIL'}, takeoff, flight and landing with finite arm reach and wrist limits. Light tools follow the balancing arm; the SDS Max keeps two hands in front.\n- [Rendered motion phases and mobile controls](${link('output/JUMP_REVIEW.md')}).\n- [Research and implementation criteria](${link('docs/JUMP_MOTION_REFERENCE.md')}).\n\nBefore the direct opening:\n\n![Blocked approach](${link('output/building-foyer-entry/before/foyer-approach.png')})\n\nAfter the direct opening:\n\n![Open approach](${link('output/building-foyer-entry/after/foyer-approach.png')})\n\n`;
report+='\n## Performance comparison\n\n'+performance.environment+' '+performance.method+'\n\nThe table reports measurements, not a universal FPS guarantee. Performance-script success means no rendering/page errors; it does not mean every frame meets 16.7 ms. Water activation includes cold shader/runtime work. JS heap is not process RAM or GPU VRAM, and its movement across scenes is affected by garbage collection; this is not a leak diagnosis. GPU timing, process RAM and VRAM were not isolated. Mobile results are desktop browser emulation, not iPhone/Safari proof.\n\n';
for(const profile of ['desktop-webgl','desktop-webgpu','portrait-webgl']){
 const before=performance.runs.find(r=>r.profile===profile&&r.version==='before'),after=performance.runs.find(r=>r.profile===profile&&r.version==='after');
 report+=`### ${profile}\n\nREADY: ${before.readyMs} → ${after.readyMs} ms. Water activation: ${before.waterActivationMs} → ${after.waterActivationMs} ms.\n\n| Scene | FPS before → after | p95 ms before → after | Max ms after | CPU mean ms after | Draw calls after | Triangles after | JS heap MB after |\n|---|---:|---:|---:|---:|---:|---:|---:|\n`;
 for(const a of after.cases){const b=before.cases.find(c=>c.name===a.name);report+=`| ${a.name} | ${n(b.fps)} → ${n(a.fps)} | ${n(b.frameMs.p95)} → ${n(a.frameMs.p95)} | ${n(a.frameMs.max)} | ${n(a.simulationCpuMs.mean)} | ${a.drawCalls} | ${a.triangles.toLocaleString('en-US')} | ${n(a.heapMB)} |\n`;}
 report+='\n';
}
report+='## Matched runtime views\n\nSame desktop viewport, camera and five-apprentice setup. Architecture and material changes are intentionally visible.\n\n';
for(const [label,pose] of [['Exterior','exterior'],['Ceiling','ceiling'],['Floor','floor']]){
 report+=`### ${label}\n\nBefore\n\n![Before ${label}](${link(`output/building-performance/desktop-webgl-before-${pose}.png`)})\n\nAfter\n\n![After ${label}](${link(`output/building-performance/desktop-webgl-after-${pose}.png`)})\n\n`;
}
report+=`Stair landing after upgrade (additional camera, not a matched comparison):\n\n![Stair landing](${link('output/building-review/final/stair-landing.png')})\n\n`;
report+='## Sources and limits\n\nRetained mansion concept and selected 5+2 section: artifacts/site-pro-04/mansion-concept. The implementation adopts stepped wings, a courtyard, deep unfinished openings, continuous concrete frame and clay infill. It is a playable interpretation, not a pixel-matched reproduction of concept lighting or composition. Structural concrete remains structural; the demolition/chase checks concern clay infill.\n\nConcrete: [Poly Haven concrete_wall_009](https://polyhaven.com/a/concrete_wall_009), Charlotte Baglioni, CC0, measured 1.8 m tile. Original diffuse/normal files and hashes retained. UV approach informed by the [Three.js texture manual](https://threejs.org/manual/pages/textures.html).\n\nTask-attributed usage/credits unavailable. Other chats were active; the account delta cannot be assigned to this task. No paid image generation or subagents.\n';
await writeFile('output/BUILDING_ACCEPTANCE.md',report);
console.log(link('output/BUILDING_ACCEPTANCE.md'));
