import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const url=process.argv[2]??'http://127.0.0.1:5365/Electrical-Game/',out=process.argv[3]??'output/water-gun';await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const report={url,mobileIsEmulation:true,fixture:'Native held input, camera test fixture. Flood time accelerated through the unmodified Game.step physics; no injected floor water.',scenarios:[]};
try{
for(const spec of [{name:'desktop',width:1366,height:768,backend:'webgpu'},{name:'mobile',width:390,height:844,mobile:true,backend:'webgpu'},{name:'webgl',width:1366,height:768,backend:'webgl'}]){
 const context=await browser.newContext({viewport:{width:spec.width,height:spec.height},isMobile:!!spec.mobile,hasTouch:!!spec.mobile,deviceScaleFactor:1});const page=await context.newPage(),errors=[];
 await page.addInitScript(()=>{const Original=window.WebSocket;window.WebSocket=class extends Original{addEventListener(type,callback,options){if(type!=='message')return super.addEventListener(type,callback,options);return super.addEventListener(type,event=>{try{if(['update','full-reload'].includes(JSON.parse(event.data).type))return;}catch{}if(typeof callback==='function')callback.call(this,event);else callback?.handleEvent(event);},options);}};});
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto(url+(spec.backend==='webgl'?'?renderer=webgl':''),{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__wireTheHouse,{timeout:120000});await page.locator('#start-button').click();await page.evaluate(async()=>{if(document.pointerLockElement)await document.exitPointerLock();});await page.waitForTimeout(100);
 if(spec.mobile)await page.locator('[data-tool="hose"]').tap();else await page.keyboard.press('Digit8');
 assert.equal(await page.locator('#water-gun-mode').inputValue(),'flood');
 await page.locator('#settings-toggle')[spec.mobile?'tap':'click']();await page.locator('#water-gun-mode').selectOption('shower');await page.locator('#settings-close')[spec.mobile?'tap':'click']();
 await page.evaluate(()=>{const g=window.__wireTheHouse,c=g.renderer.camera;c.position.set(0,g.player.eyeHeight,1.2);c.lookAt(-.25,0,-.5);g.player.yaw=c.rotation.y;g.player.pitch=c.rotation.x;g.step(0);});
 const touch=spec.mobile?await context.newCDPSession(page):null;
 async function hold(){if(touch){const b=await page.locator('#look-joystick').boundingBox();await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width*.5,y:b.y+b.height*.5,id:1}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+b.width*.5+5,y:b.y+b.height*.5,id:1}]});}else await page.keyboard.down('KeyE');}
 async function release(){if(touch)await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});else await page.keyboard.up('KeyE');}
 async function shot(name){await page.evaluate(async()=>{const g=window.__wireTheHouse;await g.renderer.waitForFrame();g.renderer.render();await g.renderer.waitForFrame();});await page.screenshot({path:`${out}/${spec.name}-${name}.png`});}
 await hold();await page.waitForFunction(()=>window.__wireTheHouse.roomWater.telemetry.floorLitres>.3,undefined,{timeout:30000});await shot('shower');
 const nozzle=await page.evaluate(()=>{const g=window.__wireTheHouse;return{error:g.roomWater.jetState.origin.distanceTo(g.fpsRig.toolTipWorld(g.renderer.camera,'hose')),alignment:g.roomWater.jetState.direction.dot(g.fpsRig.waterGunDirectionWorld())};});assert(nozzle.error<.0005);assert(nozzle.alignment>.99999);
 const shower=await page.evaluate(()=>JSON.parse(window.__wireTheHouse.renderState()).water);assert.equal(shower.active,true);assert.equal(shower.backend,spec.backend);assert.equal(shower.gunMode,'shower');assert(shower.gunLitres>0);await release();await page.waitForTimeout(100);
 const stopped=await page.evaluate(()=>window.__wireTheHouse.mortar.waterGunLitres);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>window.__wireTheHouse.mortar.waterGunLitres),stopped);
 if(spec.mobile)await page.locator('#tool-mode-toggle').tap();else {await page.evaluate(async()=>{if(document.pointerLockElement)await document.exitPointerLock();});await page.locator('#settings-toggle').click();const value=await page.locator('#water-gun-mode').inputValue();await page.locator('#water-gun-mode').selectOption(value==='shower'?'jet':'flood');await page.locator('#settings-close').click();}assert.equal(await page.locator('#water-gun-mode').inputValue(),'jet');await hold();await page.waitForTimeout(500);await shot('jet');await release();
 if(spec.mobile)await page.locator('#tool-mode-toggle').tap();else {await page.evaluate(async()=>{if(document.pointerLockElement)await document.exitPointerLock();});await page.locator('#settings-toggle').click();const value=await page.locator('#water-gun-mode').inputValue();await page.locator('#water-gun-mode').selectOption(value==='shower'?'jet':'flood');await page.locator('#settings-close').click();}assert.equal(await page.locator('#water-gun-mode').inputValue(),'flood');await hold();await page.waitForFunction(()=>window.__wireTheHouse.input.actionHeld);await shot('flood-stream');
 await page.evaluate(async()=>{const g=window.__wireTheHouse;await g.renderer.waitForFrame();const render=g.renderer.render;g.renderer.render=()=>{};try{for(let i=0;i<120;i++)g.step(.05);}finally{g.renderer.render=render;}});await shot('large-puddle');
 const accelerated=await page.evaluate(async()=>{const g=window.__wireTheHouse;await g.renderer.waitForFrame();const render=g.renderer.render;g.renderer.render=()=>{};const before=g.mortar.waterGunLitres;try{for(let i=0;i<2400;i++)g.step(.05);}finally{g.renderer.render=render;}return{before,after:g.mortar.waterGunLitres,water:g.roomWater.telemetry};});
 assert(Math.abs(accelerated.after-accelerated.before-19200)<.001);await release();await page.waitForTimeout(300);await shot('flood');
 const flood=await page.evaluate(()=>{const g=window.__wireTheHouse,p=g.roomWater.surfaceGeometry.getAttribute('position');let min=Infinity,max=0;for(let i=0;i<p.count;i++){min=Math.min(min,p.getY(i));max=Math.max(max,p.getY(i));}return{...g.roomWater.telemetry,minSurfaceY:min,maxSurfaceY:max,renderError:g.renderer.renderError,jetActive:g.roomWater.jetState.active};});
 assert(flood.floorLitres>19000);assert(flood.wetAreaM2>28);assert(flood.meanDepthMm>650);assert(flood.minSurfaceY>.5);assert(Math.abs(flood.conservationErrorLitres)<1e-5);assert.equal(flood.jetActive,false);assert.equal(flood.renderError,'');assert.deepEqual(errors,[]);
 await page.locator('#settings-toggle')[spec.mobile?'tap':'click']();await page.locator('#water-gun-mode').selectOption('mist');await shot('settings');await page.locator('#settings-close')[spec.mobile?'tap':'click']();assert.equal(await page.locator('#water-gun-mode').inputValue(),'mist');
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);
 report.scenarios.push({name:spec.name,shower,accelerated,flood,errors});console.log(JSON.stringify(report.scenarios.at(-1)));await context.close();
}
}finally{await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));await browser.close();}
