import assert from 'node:assert/strict';import{chromium}from'playwright';import{blockPointerLock}from'./browser-safety.mjs';import{mkdir,writeFile}from'node:fs/promises';
const url='http://127.0.0.1:5362/Electrical-Game/',out='output/wet-wall-ui';await mkdir(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true});const report={url,fixture:'Native held keyboard or CDP touch spray. Deterministic camera sweep and 60 Hz Game.step fixture; no injected water or wet material. Mobile is Chrome emulation, not physical iPhone.',scenarios:[]};
try{for(const spec of[{name:'desktop',mobile:false},{name:'mobile',mobile:true},{name:'desktop-webgl',mobile:false,webgl:true}]){
const context=await b.newContext({viewport:spec.mobile?{width:390,height:844}:{width:1366,height:768},isMobile:spec.mobile,hasTouch:spec.mobile,deviceScaleFactor:1});await blockPointerLock(context);const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto(url+(spec.webgl?'?renderer=webgl':''),{waitUntil:'networkidle'});await p.waitForFunction(()=>window.__wireTheHouse?.roomWater.waterProActive,undefined,{timeout:120000});await p.locator('#start-button')[spec.mobile?'tap':'click']();await p.locator('#start-screen').waitFor({state:'hidden'});if(spec.mobile)await p.locator('[data-tool="hose"]').tap();else await p.keyboard.press('Digit8');
await p.evaluate(()=>{const g=window.__wireTheHouse;window.__wetStep=g.step.bind(g);g.step=()=>{};window.__absorbed=0;const apply=g.mortar.applyWater.bind(g.mortar);g.mortar.applyWater=(...a)=>{const r=apply(...a);window.__absorbed+=r.absorbedLitres;return r;};g.renderer.camera.position.set(0,1.65,-.4);g.renderer.camera.lookAt(0,1.65,-2.41);g.player.yaw=g.renderer.camera.rotation.y;g.player.pitch=g.renderer.camera.rotation.x;window.__wetStep(1/60);});await p.evaluate(async()=>{await window.__wireTheHouse.renderer.waitForFrame();});await p.screenshot({path:`${out}/${spec.name}-dry.png`});
const cdp=spec.mobile?await context.newCDPSession(p):null;if(cdp){const box=await p.locator('#look-joystick').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2,id:17}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+box.width/2+5,y:box.y+box.height/2,id:17}]});}else await p.keyboard.down('KeyE');
const rows=[];for(let row=0;row<14;row++)rows.push(await p.evaluate(row=>{const g=window.__wireTheHouse,times=[];for(let col=0;col<27;col++){g.renderer.camera.lookAt(-1.3+col*.1,.5+row*.15,-2.41);g.player.yaw=g.renderer.camera.rotation.y;g.player.pitch=g.renderer.camera.rotation.x;const start=performance.now();window.__wetStep(1/60);times.push(performance.now()-start);}return{row,cells:g.mortar.water.size,upper:[...g.mortar.water.values()].filter(c=>c.position.y>2).length,litres:g.mortar.waterGunLitres,stepTimes:times};},row));
if(cdp)await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});else await p.keyboard.up('KeyE');
await p.evaluate(()=>{const g=window.__wireTheHouse;g.renderer.camera.lookAt(0,1.65,-2.41);g.player.yaw=g.renderer.camera.rotation.y;g.player.pitch=g.renderer.camera.rotation.x;for(let i=0;i<180;i++)window.__wetStep(1/60);g.step=window.__wetStep;});await p.evaluate(async()=>{await window.__wireTheHouse.renderer.waitForFrame();});await p.waitForFunction(()=>window.__wireTheHouse.mortar.pendingWetGeometry===0);await p.screenshot({path:`${out}/${spec.name}-wet.png`});
const data=await p.evaluate(()=>{const g=window.__wireTheHouse,m=g.mortar;return{cells:m.water.size,drawCalls:m.telemetry.wetDrawCalls,upper:[...m.water.values()].filter(c=>c.position.y>2&&c.pore>.8).length,empty:[...m.water.values()].filter(c=>!c.patch.count).length,litres:m.waterGunLitres,absorbed:window.__absorbed,room:g.roomWater.telemetry,renderError:g.renderer.renderError,overflow:document.documentElement.scrollWidth>innerWidth,held:g.input.actionHeld,pointerLock:!!document.pointerLockElement};});
const sorted=rows.flatMap(r=>r.stepTimes).sort((a,b)=>a-b);data.stepMs={p50:sorted[Math.floor(sorted.length*.5)],p95:sorted[Math.floor(sorted.length*.95)],max:sorted.at(-1)};assert(data.cells>900,`${spec.name}: sweep still saturates the old cell limit`);assert(data.upper>150,`${spec.name}: upper sprayed bricks remain dry`);assert(data.drawCalls<12,`${spec.name}: wet cells generate excessive draw calls`);assert(Math.abs(data.litres-data.absorbed-data.room.receivedLitres)<1e-6,`${spec.name}: source/absorption/runoff conservation`);assert(Math.abs(data.room.conservationErrorLitres)<1e-6);assert.equal(data.held,false);assert.equal(data.pointerLock,false);assert.equal(data.overflow,false);assert.equal(data.renderError,'');assert.deepEqual(errors,[]);report.scenarios.push({...spec,...data,rows,errors});console.log(JSON.stringify({name:spec.name,cells:data.cells,upper:data.upper,drawCalls:data.drawCalls,litres:data.litres,stepMs:data.stepMs}));await context.close();}
}finally{await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));await b.close();}
